##########################################
# Board Definition
##########################################

if(${CHIPSET} STREQUAL "tcc803x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER ON)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_VPU_C7_INCLUDE)
	add_definitions(-DTCC_HEVC_INCLUDE)
	add_definitions(-DTCC_JPU_C6_INCLUDE)
	add_definitions(-DUSE_COMMON_KERNEL_LOCATION)
elseif(${CHIPSET} STREQUAL "tcc805x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER ON)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_JPU_C6_INCLUDE)
	add_definitions(-DTCC_VPU_C7_INCLUDE)
	add_definitions(-DTCC_VPU_4K_D2_INCLUDE)
	add_definitions(-DTCC_VPU_4K_E1_INCLUDE)
	add_definitions(-DUSE_COMMON_KERNEL_LOCATION)
elseif(${CHIPSET} STREQUAL "tcc807x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER ON)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_JPU_C6_INCLUDE)
	add_definitions(-DTCC_VPU_C7_INCLUDE)
	add_definitions(-DTCC_VPU_4K_D2_INCLUDE)
	add_definitions(-DTCC_VPU_4K_E1_INCLUDE)
	add_definitions(-DUSE_COMMON_KERNEL_LOCATION)
elseif(${CHIPSET} STREQUAL "tcc897x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER ON)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_JPU_C6_INCLUDE)
	add_definitions(-DTCC_VPU_D6_INCLUDE)
	add_definitions(-DTCC_HEVC_INCLUDE)
	add_definitions(-DUSE_COMMON_KERNEL_LOCATION)
elseif(${CHIPSET} STREQUAL "tcc802x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER ON)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_JPU_C6_INCLUDE)
	add_definitions(-DTCC_VPU_C7_INCLUDE)
elseif(${CHIPSET} STREQUAL "tcc750x")
	set(USE_VPU_LEGACY ON)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER OFF)
	set(USE_ENCODER ON)

	add_definitions(-DTCC_VPU_4K_E1_INCLUDE)
	add_definitions(-DUSE_COMMON_KERNEL_LOCATION)
else()
	message("compile_definition.cmake: Error unsupported chipset ${CHIPSET}")

	set(USE_VPU_LEGACY OFF)
	set(USE_VPU_V3 OFF)
	set(USE_DECODER OFF)
	set(USE_ENCODER OFF)
endif()

if(${SUPPORT_4K_VIDEO} STREQUAL "enable")
	add_definitions(-DSUPPORT_4K_VIDEO)
endif()
